### ISSUE TITLE
Specific Data

### ISSUE THREAD

**Issue by willuk2010** [EMCECS/ecs-sync#10]
Can this tool be used to pull specific objects (audio file, and metadata) from Atmos to my local machine? if I *somehow* fed in a list of the object ID's im interested in?

**Comment by twincitiesguy** [comment]
Yes, but if they were stored with a namespace path, that would be better.  Otherwise the local filenames will just be the object IDs.  The AtmosSource has `--source-oid-list <filename>` and `--source-name-list <filename>` options to specify a list file of OIDs and namespace paths respectively.

The command might look like this:
`java -jar ecs-sync-2.1.jar --source atmos:https://<uid>:<secret>@<host> --target file:///Users/username/Documents --source-oid-list object-ids.lst`
