### ISSUE TITLE
Questions about data flow and sequence of the work

### ISSUE THREAD

**Issue by imtester1** [EMCECS/ecs-sync#106]
I'm working on a migration using ECS-SYNC and I have a question.

I am curious about the order of operations and data flow.

First, the order of work is
1. Create a Clip-ID list.
2. Create an xml file.
3. Start the task with the ecs-sync-ctl --submit <path> command.
I understand it.

The data flow is
1. The sync server requests Centera with the clip-id list.
2. Centera sends data to the sync server.
3. The sync server delivers the received data to ecs.
4. Verify the data in the above process.
5. Done

Am I understanding this correctly?

**Comment by hoelgu** [comment]
Hi 

 

Lot’s of things are going to be happening in parallel and not in a sequence.

Once the first clips are in the database, ECSSync begins to read them from the source, write them to the target, read them from the target, compare the MD5 values to ensure that nothing has changed.

Make sure to check the enhanced db entries checkbox so that you have the MD5 values and can prove that nothing has changed.

If you still migrate off of Centera, make sure to watch the number of connections on the access nodes, typically we have seen roughly 2.5 to 3 times as many connections on the access nodes as threads configured in ECSSync. You can easily overwhelm a small Centera with a single ECSSync VM. 

In case of any questions, reach out to ***@***.***

 

Take care, Holger

 

Holger Jakob
Head of Unstructured Data Solutions

Tel.  <tel:+41315113600> +41 79 415 56 22 

 <https://www.backup.ch/> 

 

From: jyjung05 ***@***.***> 
Sent: Friday, 15 December 2023 06:28
To: EMCECS/ecs-sync ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EMCECS/ecs-sync] Questions about data flow and sequence of the work (Issue #106)

 

I'm working on a migration using ECS-SYNC and I have a question.

I am curious about the order of operations and data flow.

First, the order of work is

1.	Create a Clip-ID list.
2.	Create an xml file.
3.	Start the task with the ecs-sync-ctl --submit command.
I understand it.

The data flow is

1.	The sync server requests Centera with the clip-id list.
2.	Centera sends data to the sync server.
3.	The sync server delivers the received data to ecs.
4.	Verify the data in the above process.
5.	Done

Am I understanding this correctly?

**Comment by imtester1** [comment]
During the migration process, is Centera's data directly transferred to ECS without going through the ECS-Sync server?

**Comment by hoelgu** [comment]
You could achieve that with a native transformation. I find ECSSync more controllable and less risky to overload the Centera, especially if it is a small one.

Reach out to ***@***.*** if we can be of any assistance

Holger


Holger Jakob
+41 79 415 56 22

On 17 Dec 2023, at 13:06, testmeyout ***@***.***> wrote:

﻿

During the migration process, is Centera's data directly transferred to ECS without going through the ECS-Sync server?

**Comment by imtester1** [comment]
Thanks for you
