### ISSUE TITLE
MySQLDbService: could not create DB table objects. note: name may only contain alphanumeric or underscore

### ISSUE THREAD

**Issue by jonathanw42** [EMCECS/ecs-sync#34]
Based on the error, it appears a sync will not work if the filename/path has characters other than alphanumeric or underscores. Since I have a path with slashes and a dash in the filename for the date, I am seeing this error. Is there a workaround or some way to pre-process to rename?

**Comment by jrosenth** [comment]
That would appear to be a MySQL limitation.  Not Ecs-sync.

You could try escaping the "-" properly (see MySQL docs ).


Jay

**Comment by twincitiesguy** [comment]
I would check the entire stacktrace of the error.  That message is only a hint at what the problem might be.

Note that the problem is not in the table name though because it is using a name of “objects” (the default if you do not provide a name via the CLI or XML configuration).

My guess is you’ve provided a MySQL connection string but are not running MySQL or the connection string is wrong.

**Comment by twincitiesguy** [comment]
Assuming this is resolved.
