### ISSUE TITLE
Enhancement Request : be able to archive a job from ecs-sync-ctl

### ISSUE THREAD

**Issue by lriva94** [EMCECS/ecs-sync#79]
Currently in ecs-sync 3.4, it is only possible to archive a job through the GUI.
As generally I only have access to the ecs-sync servers through CLI, it would be more efficient to have the possibility to archive jobs though CLI, like ecs-sync-ctl --archive <jobid>.
It is because the list of jobs displayed and memorized cannot be more that 10, unless there is a config file where this value of 10 may be increased.

**Comment by twincitiesguy** [comment]
Archiving a job will collect summary, error report, and configuration data and save them for reference later, then delete the job from the ecs-sync active job list.  However, the "archive" portion of that function is specific to the UI application and is not baked into the ecs-sync service.

If you have reached the limit of 10 active jobs and are _not_ using the UI, then you need to delete a completed job to free up a slot for a new job (`ecs-sync-ctl --delete <job-id>`).  If you want to preserve the job data for later reference, you'll have to do that yourself before deleting, since that is not a function of the service.
