### ISSUE TITLE
Unable to download the UI files as they are .jar

### ISSUE THREAD

**Issue by Mikeguy74** [EMCECS/ecs-sync#83]
Is there another way to get the UI files other than in .jar format?  Is there a way to get them .zip format?  I tried downloading using the green Code button under <>Code, but when I try to run the install I am getting the error:

Cannot find jar files.  Please run this script from within the exploded distribution package.

I had moved the ecs-sync-master.zip to the server (CentOS7) and then unzipped it.  I have tried running this at several different directory, and each time it gives the same error.  I am running the command as root.

Maybe I just need to move the files to a different directory?  I moved the ecs-sync-master.zip to the /home/ directory.

**Comment by xiaoxin-ren** [comment]
ecs-sync-master.zip is source code, you'll go to https://github.com/EMCECS/ecs-sync/releases and find the latest binary whose name is ecs-sync-3.4.2.zip. Unzip ecs-sync-3.4.2.zip and put ecs-sync-ui-3.4.2.jar into directory ecs-sync-3.4.2/.

**Comment by Mikeguy74** [comment]
Is there a format for ecs-sync-ui-3.4.2.jar other than .jar?  Is there a .zip?  I am not able to directly download .jar files per my company's Security settings.

**Comment by xiaoxin-ren** [comment]
ecs-sync-ui-3.4.2.jar is not mandatory in order to run ecs-sync, i.e. the user could run ecs sync without UI jar being installed. CLI command ecs-sync-ctl if ui jar will be used in this case, please see details in https://github.com/EMCECS/ecs-sync/wiki/Running-a-Sync. 
It's recommended to deploy UI jar for more friendly experience, you might find alternative ways to download it or generate it by building from source code.

**Comment by twincitiesguy** [comment]
Unfortunately, there is no other deliverable binary we publish.  You can optionally clone this repo and build the UI jar yourself using the following command:
(inside the `ecs-sync-ui` subdirectory)
```
./grailsw prod package
```
